### ISSUE TITLE
请问怎么配置飞书事件订阅-请求地址配置？

### ISSUE THREAD

**Issue by PipelineMaster** [ripples-alive/Feishu-ChatGPT#1]

**Comment by ripples-alive** [comment]
<img width="557" alt="WeChat0141c1e0cc2b059b54d67563b45ee462" src="https://user-images.githubusercontent.com/7439574/220606412-3f35a333-e673-4d93-a721-5c07fbddd041.png">

这里改成 `http://<服务器ip>:8000/webhook/chatgpt`
