### ISSUE TITLE
写错了么，应该是 webhook/chatgpt  ？

### ISSUE THREAD

**Issue by lmmsoft** [ripples-alive/Feishu-ChatGPT#4]
Q1: 写错了么，应该是 webhook/chatgpt ？

https://github.com/ripples-alive/Feishu-ChatGPT/blob/0808f73b767b7489bdfa4a587ba4f5b53bfa3031/src/bot.py#L281

Q2: 事件订阅，里面应该订阅哪些事件？

Q3: loading_img 怎么上传呀？

**Comment by ripples-alive** [comment]
Q1: 复制的官方样例改的，注释忘了改了
Q2: 接收消息v2.0
Q3: 随便编辑一个消息卡片，左边栏模块组件里面有图片组件，插入之后就可以看到上传图片，选择对应的应用上传，右边栏里就能看到 key 了

![image](https://user-images.githubusercontent.com/7439574/222634426-e7a389b8-354a-4ec7-9fea-5d949e7af0b5.png)

**Comment by lmmsoft** [comment]
Thanks for the reply~
